name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/build.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  VERSION: 0.7.3.${{ github.run_number }}

jobs:
  build:
    name: 👌 Verify build
    runs-on: ubuntu-latest
    steps:    
    - name: 🛒 Checkout repository
      uses: actions/checkout@v3        
    - name: 🛠️ Build
      run: dotnet build -c Release src/Refitter.sln -p:UseSourceLink=true -p:PackageVersion="${{ env.VERSION }}" -p:Version="${{ env.VERSION }}"
    - name: 🧪 Test
      run: dotnet test src/Refitter.sln -c Release    
    - name: 🗳️ Upload
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: |
          **/*.nupkg
          README.md

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install github_changelog_generator
        run: gem install github_changelog_generator
      - name: Re-generate CHANGELOG.md
        run: github_changelog_generator --user christianhelle --project refitter --token ${{ secrets.PAT }}
      - name: Git commit CHANGELOG.md
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "Continuous Integration"
          git config --global user.email "username@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for build v${{ env.VERSION }}"
          git push
