name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/build.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Build
      run: dotnet build src/Refitter.sln -c Release
    - name: Test
      run: dotnet test src/Refitter.sln --no-build --no-restore -c Release
    - name: Package
      run: dotnet pack src/Refitter.sln --no-build --no-restore -c Release
    - name: Publish
      run: dotnet publish src/Refitter/Refitter.csproj --no-build --no-restore -c Release
