name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/build.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  VERSION: 0.6.3.${{ github.run_number }}

jobs:
  build:
    name: 👌 Verify build
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v2    
    - name: 🛠️ Build
      run: dotnet build src/Refitter.sln -c Release -p:UseSourceLink=true -p:PackageVersion="${{ env.VERSION }}"
    - name: 🧪 Test
      run: dotnet test src/Refitter.sln --no-build --no-restore -c Release
    - name: 🗳️ Upload
      uses: actions/upload-artifact@v3
      with:
        name: CLI Tool
        path: |
          **/*.nupkg
          README.md
