name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/build.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  VERSION: 0.7.3.${{ github.run_number }}

jobs:
  build:
    name: 👌 Verify build
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v3    
    - name: 🛠️ Build
      run: dotnet build src/Refitter.sln -c Release -p:UseSourceLink=true -p:PackageVersion="${{ env.VERSION }}"
    - name: 🧪 Test
      run: dotnet test src/Refitter.sln -c Release --collect "Code coverage"
    - name: 🗳️ Upload
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: |
          **/*.nupkg
          README.md
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
