name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/msbuild.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/msbuild.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - '*'

jobs:
  build:
    name: 👌 Verify build
    runs-on: ubuntu-latest
    steps:    
    - name: 🛒 Checkout repository
      uses: actions/checkout@v4
    - name: 🛠️ Prepare
      working-directory: test/MSBuild
      run: |
        dotnet restore ../../src/Refitter.MSBuild/Refitter.MSBuild.csproj
        dotnet build -c release ../../src/Refitter.MSBuild/Refitter.MSBuild.csproj
        dotnet pack -c release ../../src/Refitter.MSBuild/Refitter.MSBuild.csproj -o
        nuget add .\Refitter.MSBuild.1.0.0.nupkg -source .
        dotnet add package Refitter.MSBuild -s .
    - name: 🛠️ Build
      working-directory: test/MSBuild
      run: dotnet build -v d -filelogger
    - name: 🧪 Build Output
      working-directory: test/MSBuild
      run: cat msbuild.log
