name: Production Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/production-tests.yml"
    branches:
      - "main"
  schedule:
    - cron: '0 2 * * *'

jobs:

  cli:
    strategy:
      fail-fast: false
      matrix:
        format: [json, yaml]
        version: [v2.0, v3.0]
        os: [macos-latest, windows-latest, ubuntu-latest]
        openapi: [
          "api-with-examples",
          "callback-example",
          "link-example",
          "uber",
          "uspto",
          "petstore",
          "petstore-expanded",
          "petstore-minimal",
          "petstore-simple",
          "petstore-with-external-docs",
          "hubspot-events",
          "hubspot-webhooks"
        ]
    uses: ./.github/workflows/template.yml
    with:
      os: ${{ matrix.os }}
      format: ${{ matrix.format }}
      version: ${{ matrix.version }}
      openapi: ${{ matrix.openapi }}
      command: 'dotnet tool install --global --prerelease refitter; refitter'

  sourcegenerator:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]        
    uses: ./.github/workflows/template-source-generator.yml
    with:
      os: ${{ matrix.os }}
