name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

jobs:
  url:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 0.7.0
      nuget_key: ${{ secrets.NUGET_KEY }}