name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/smoke-tests.yml"
      - "!.github/workflows/template.yml"
      - "!src/**/*.csproj"
      - "!src/**/*.cs"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  template:
    strategy:
      matrix:
        format: [json, yaml]
        version: [v2.0, v3.0]
        os: [ubuntu-latest]
        openapi: ["callback-example", "link-example", "uber", "uspto", "petstore"]
    uses: ./.github/workflows/template.yml
    with:
      format: ${{ matrix.format }}
      version: ${{ matrix.version }}
      openapi: ${{ matrix.openapi }}
      os: ${{ matrix.os }}
      command: 'dotnet run --project ../src/Refitter/Refitter.csproj'
