name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - '!src/Refitter/**/*.cs'
      - '!src/Refitter.Core/**/*.cs'
      - '!src/Refitter.SourceGenerator/**/*.cs'
      - '!src/Refitter/**/*.csproj'
      - '!src/Refitter.Core/**/*.csproj'
      - '!src/Refitter.SourceGenerator/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
      - "!test/smoke-tests.ps1"
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**/*"
      - '!src/Refitter/**/*.cs'
      - '!src/Refitter.Core/**/*.cs'
      - '!src/Refitter.SourceGenerator/**/*.cs'
      - '!src/Refitter/**/*.csproj'
      - '!src/Refitter.Core/**/*.csproj'
      - '!src/Refitter.SourceGenerator/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
      - "!test/smoke-tests.ps1"
    branches:
      - "*"

jobs:
  
  script:
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v4

    - name: 🛠️ Run smoke test script
      run: ./smoke-tests.ps1
      working-directory: test
      shell: pwsh
