name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!**/*.cs"
      - "!**/*.csproj"
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  
  file:

    strategy:
      fail-fast: false
      matrix:
        format: [json, yaml]
        version: [v2.0, v3.0]
        os: [ubuntu-latest]
        openapi: [
          "callback-example",
          "link-example",
          "uber",
          "uspto",
          "petstore",
          "petstore-expanded",
          "ingram-micro"
        ]
    
    uses: ./.github/workflows/template.yml
    with:
      format: ${{ matrix.format }}
      version: ${{ matrix.version }}
      openapi: ${{ matrix.openapi }}
      os: ${{ matrix.os }}
      command: 'dotnet run --project ../src/Refitter/Refitter.csproj'
  
  url:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        openapi_url: [
          "https://petstore3.swagger.io/api/v3/openapi.json", 
          "https://petstore3.swagger.io/api/v3/openapi.yaml",
          "https://api.hubspot.com/api-catalog-public/v1/apis/events/v3/send",
          "https://api.hubspot.com/api-catalog-public/v1/apis/webhooks/v3"
        ]

    uses: ./.github/workflows/template-url.yml
    with:
      os: ${{ matrix.os }}
      openapi: ${{ matrix.openapi_url }}
      command: 'dotnet run --project ../src/Refitter/Refitter.csproj'
