name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - '!src/Refitter/**/*.cs'
      - '!src/Refitter.Core/**/*.cs'
      - '!src/Refitter.SourceGenerator/**/*.cs'
      - '!src/Refitter/**/*.csproj'
      - '!src/Refitter.Core/**/*.csproj'
      - '!src/Refitter.SourceGenerator/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**/*"
      - '!src/Refitter/**/*.cs'
      - '!src/Refitter.Core/**/*.cs'
      - '!src/Refitter.SourceGenerator/**/*.cs'
      - '!src/Refitter/**/*.csproj'
      - '!src/Refitter.Core/**/*.csproj'
      - '!src/Refitter.SourceGenerator/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
    branches:
      - "*"

jobs:
  
  file:
    strategy:
      fail-fast: false
      matrix:
        framework: [net8.0]
        format: [json, yaml]
        version: [v2.0, v3.0]
        os: [ubuntu-latest]
        openapi: [
          "api-with-examples",
          "callback-example",
          "link-example",
          "uber",
          "uspto",
          "petstore",
          "petstore-expanded",
          "petstore-minimal",
          "petstore-simple",
          "petstore-with-external-docs",
          "hubspot-events",
          "hubspot-webhooks",
          "bot.paths"
        ]
    
    uses: ./.github/workflows/template.yml
    with:
      format: ${{ matrix.format }}
      version: ${{ matrix.version }}
      openapi: ${{ matrix.openapi }}
      os: ${{ matrix.os }}
      command: dotnet run --project ../src/Refitter/Refitter.csproj --framework ${{ matrix.framework }}
  
  url:
    strategy:
      fail-fast: false
      matrix:
        framework: [net8.0]
        os: [ubuntu-latest]
        openapi_url: [
          "https://petstore3.swagger.io/api/v3/openapi.json", 
          "https://petstore3.swagger.io/api/v3/openapi.yaml"
        ]

    uses: ./.github/workflows/template-url.yml
    with:
      os: ${{ matrix.os }}
      openapi: ${{ matrix.openapi_url }}
      command: dotnet run --project ../src/Refitter/Refitter.csproj --framework ${{ matrix.framework }}
