name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - '!src/Refitter/**/*.cs'
      - '!src/Refitter.Core/**/*.cs'
      - '!src/Refitter.SourceGenerator/**/*.cs'
      - '!src/Refitter/**/*.csproj'
      - '!src/Refitter.Core/**/*.csproj'
      - '!src/Refitter.SourceGenerator/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
      - "!tests/smoke-tests.ps1"
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**/*"
      - '!src/Refitter/**/*.cs'
      - '!src/Refitter.Core/**/*.cs'
      - '!src/Refitter.SourceGenerator/**/*.cs'
      - '!src/Refitter/**/*.csproj'
      - '!src/Refitter.Core/**/*.csproj'
      - '!src/Refitter.SourceGenerator/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
      - "!tests/smoke-tests.ps1"
    branches:
      - "*"

jobs:
  
  script:
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v4

    - name: 🛠️ Run smoke test script
      run: ./smoke-test.ps1
      working-directory: test
      shell: pwsh
  
  url:
    strategy:
      fail-fast: false
      matrix:
        framework: [net8.0]
        os: [ubuntu-latest]
        openapi_url: [
          "https://petstore3.swagger.io/api/v3/openapi.json", 
          "https://petstore3.swagger.io/api/v3/openapi.yaml"
        ]

    uses: ./.github/workflows/template-url.yml
    with:
      os: ${{ matrix.os }}
      openapi: ${{ matrix.openapi_url }}
      command: dotnet run --project ../src/Refitter/Refitter.csproj --framework ${{ matrix.framework }}

  apizr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v4

    - name: 🛠️ Generate code
      run: dotnet run --project ../../src/Refitter/Refitter.csproj --framework net8.0 -- --settings-file petstore.apizr.refitter --no-logging
      working-directory: test/Apizr

    - name: 🛠️ Build
      run: dotnet build Sample.csproj
      working-directory: test/Apizr

