name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!**/*.cs"
      - "!**/*.csproj"
      - "!.github/workflows/template.yml"
      - "!.github/workflows/smoke-tests.yml"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  template:
    strategy:
      fail-fast: false
      matrix:
        format: [json, yaml]
        version: [v2.0, v3.0]
        os: [ubuntu-latest]
        openapi: ["callback-example", "link-example", "uber", "uspto", "petstore", "ingram-micro"]
    uses: ./.github/workflows/template.yml
    with:
      format: ${{ matrix.format }}
      version: ${{ matrix.version }}
      openapi: ${{ matrix.openapi }}
      os: ${{ matrix.os }}
      command: 'dotnet run --project ../src/Refitter/Refitter.csproj'
      
  template:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        openapi: [
          "https://petstore3.swagger.io/api/v3/openapi.json", 
          "https://petstore3.swagger.io/api/v3/openapi.yaml"
        ]
    uses: ./.github/workflows/template-url.yml
    with:
      openapi: ${{ matrix.openapi }}
      os: ${{ matrix.os }}
      command: 'dotnet run --project ../src/Refitter/Refitter.csproj'
