name: Run Tests

on:
  workflow_call:
    inputs:
      format:
        required: true
        type: string
      version:
        required: true
        type: string
      openapi:
        required: true
        type: string
      os:
        type: string
        default: ubuntu-latest
        

jobs:
  
  test:

    name: C#
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Prepare OpenAPI Spec
      id: prepare_openapi_spec
      run: |
        $filename = "./OpenAPI/${{ inputs.version }}/${{ inputs.openapi }}.${{ inputs.format }}"
        $exists = Test-Path -Path $filename -PathType Leaf
        if ($exists -eq $true) {
          Copy-Item $filename ./openapi.${{ inputs.format }}
          "exists=$true" >> $env:GITHUB_OUTPUT
        } else {
          "exists=$false" >> $env:GITHUB_OUTPUT
        }
      working-directory: test
      shell: pwsh

    - name: Generate code
      run: |
        dotnet run --project ../src/Refitter/Refitter.csproj ./openapi.${{ inputs.format }} --namespace GeneratedCode
        cp ./Output.cs ./OpenAPI/${{ inputs.version }}/${{ inputs.openapi }}.${{ inputs.format }}.cs
        cp ./Output.cs ./ConsoleApp/Net6/Output.cs
        cp ./Output.cs ./ConsoleApp/Net7/Output.cs
        cp ./Output.cs ./ConsoleApp/Net48/Output.cs
        cp ./Output.cs ./ConsoleApp/Net472/Output.cs
        cp ./Output.cs ./ConsoleApp/Net462/Output.cs
        cp ./Output.cs ./ConsoleApp/Net481/Output.cs
        cp ./Output.cs ./ConsoleApp/NetStandard20/Output.cs
        cp ./Output.cs ./ConsoleApp/NetStandard21/Output.cs
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'
    
    - name: Publish generated code as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Generated Code (${{ inputs.openapi }}.${{ inputs.format }}, ${{ inputs.version }}, ${{ inputs.os }})
        path: test/Output.cs
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET 6 generated code
      run: dotnet build ./ConsoleApp/Net6/Net6.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET 7 generated code
      run: dotnet build ./ConsoleApp/Net7/Net7.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET 4.8.1 generated code
      run: dotnet build ./ConsoleApp/Net481/Net481.csproj
      if: steps.prepare_openapi_spec.outputs.exists == 'True' && ${{ inputs.os == 'windows-2022' }}
      working-directory: test

    - name: Build .NET 4.8 generated code
      run: dotnet build ./ConsoleApp/Net48/Net48.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET 4.7.2 generated code
      run: dotnet build ./ConsoleApp/Net472/Net472.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET 4.6.2 generated code
      run: dotnet build ./ConsoleApp/Net462/Net462.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET Standard 2.0 generated code
      run: dotnet build ./ConsoleApp/NetStandard20/NetStandard20.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'

    - name: Build .NET Standard 2.1 generated code
      run: dotnet build ./ConsoleApp/NetStandard21/NetStandard21.csproj
      working-directory: test
      if: steps.prepare_openapi_spec.outputs.exists == 'True'